version: 0.2

phases:
  build:
    commands:
	  - echo Build started on `date`
      - mvn clean
      - mvn install
artifacts:
  files:
    - appspec.yml
    - 'target/coronavirus-tracker-0.0.1-SNAPSHOT.jar'